[parameters]
seed = 0
region = "leeds"
zone_id = "OA21CD"
travel_times = true # Only set to true if you have travel time matrix at the level specified in boundary_geography
boundary_geography = "OA"
boundary_filter_column = "LEP22NM1"
boundary_filter_values = ["Leeds City Region"]


[work_assignment]
use_percentages = false
weight_max_dev = 0.0
weight_total_dev = 1.0
max_zones = 4
