[parameters]
seed = 0
region = "greater-london"
zone_id = "OA21CD"
travel_times = false      # Only set to true if you have travel time matrix at the level specified in boundary_geography
boundary_geography = "OA"

[matching]
load_hh = false
load_ind = false
n_matches = 10

[work_assignment]
use_percentages = false
weight_max_dev = 0.0
weight_total_dev = 1.0
max_zones = 4
