[parameters]
seed = 0
region = "leeds"
number_of_households = 5000
zone_id = "OA21CD"
travel_times = true # Only set to true if you have travel time matrix at the level specified in boundary_geography
boundary_geography = "OA"

[work_assignment]
use_percentages = true
weight_max_dev = 0.2
weight_total_dev = 0.8
max_zones = 8
