[parameters]
seed = 0
region = "greater-london"
zone_id = "MSOA21CD"
travel_times = false
boundary_geography = "MSOA"
nts_years = [2019, 2021, 2022]
nts_regions = ["London"]
nts_day_of_week = 3
output_crs = 4326

[work_assignment]
use_percentages = true
weight_max_dev = 0.0
weight_total_dev = 1.0
max_zones = 4
commute_level = "MSOA"

[matching]
required_columns = ["number_adults", "number_children"]
optional_columns = [
    "number_cars",
    "num_pension_age",
    "rural_urban_2_categories",
    "employment_status",
    "tenure_status",
]
n_matches = 10
chunk_size = 50000

[postprocessing]
pam_jitter = 30
pam_min_duration = 10
